branch-defaults:
  default:
    environment: idealo-design-env
    group_suffix: null
global:
  application_name: idealo-design
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
