export {default as AssetsPage} from './AssetsPage'
export {default as CompoundsPage} from './CompoundsPage'
export {default as ElementsPage} from './ElementsPage'
export {default as FoundationsPage} from './FoundationsPage'
export {default as OtherPage} from './OtherPage'
export {default as WelcomePage} from './WelcomePage'
export {default as BlogPage} from './BlogPage'
