---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: design-system-ui-via-f5
  namespace: design-system
  annotations:
    kubernetes.io/ingress.class: "f5"
    virtual-server.f5.com/ip: "controller-default"
 
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/allow-http: "false"

    virtual-server.f5.com/health: |
      [
        {
          "path":     "design.k8s-dpg.eu.idealo.com/",
          "send":     "GET / HTTP/1.0\r\n",
          "interval": 5,
          "timeout":  10
        }
      ]
spec:
 tls:
   - secretName: "/Common/ssl_client_wildcard_k8s-dpg_eu_idealo_com"
 rules:
 - host: design.k8s-dpg.eu.idealo.com
   http:
     paths:
       - path: /
         backend:
           serviceName: design-system-ui
           servicePort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: design-system
  name: design-system-deployment
  labels:
    app: design-system-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: design-system-ui
  template:
    metadata:
      labels:
        app: design-system-ui
    spec:
      containers:
      - name: nginx
        image: repo.eu.idealo.com:5101/design-system-ui
        ports:
        - containerPort: 8080

