name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_test: #1 
    runs-on: ubuntu-latest #1 
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo #1
        uses: actions/checkout@v2 #1
      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: |
          npm ci
          npm run test:unit
          npm run test:scripts
          npm run test:consumer
          DANGEROUS_TEST_MODE_ARGUMENT=true npm run test:provider
          npm run build