name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: |
          cd packages/idealo.design
          npm ci
          DANGEROUS_TEST_MODE_ARGUMENT=true npm run test:unit
          DANGEROUS_TEST_MODE_ARGUMENT=true npm run test:consumer
          DANGEROUS_TEST_MODE_ARGUMENT=true npm run test:provider

  upload-to-beanstalk:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create package
        run: pushd ./packages/idealo.design && zip -r deploy.zip . -x '*.git*' && popd && mv ./packages/idealo.design/deploy.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v17
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: idealo-design
          environment_name: idealo-design-env
          version_label: ${{github.SHA}}
          version_description: ${{github.SHA}}
          region: eu-central-1
          deployment_package: deploy.zip
          wait_for_deployment: true
          use_existing_version_if_available: true
