name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-CI
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build_and_push_to_registry
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          
      - name: Do something with a passing CI
        if: steps.wait-for-CI.outputs.conclusion == 'success'
        uses: actions/checkout@v2
      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: |
          cd packages/idealo.design
          npm ci
          DANGEROUS_TEST_MODE_ARGUMENT=true npm run test:unit
          DANGEROUS_TEST_MODE_ARGUMENT=true npm run test:consumer
          DANGEROUS_TEST_MODE_ARGUMENT=true npm run test:provider

  upload-to-beanstalk:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          
      - name: Do something with a passing CI & Check out the repo
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: actions/checkout@v2

      - name: Create package
        run: pushd ./packages/idealo.design && zip -r deploy.zip . -x '*.git*' && popd && mv ./packages/idealo.design/deploy.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v17
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: idealo-design
          environment_name: idealo-design-env
          version_label: ${{github.SHA}}
          version_description: ${{github.SHA}}
          region: eu-central-1
          deployment_package: deploy.zip
          wait_for_deployment: true
