name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  upload-to-beanstalk:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v17
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: idealo.design
          environment_name: Idealodesign-env
          version_label: 123
          version_description: ${{github.SHA}}
          region: eu-central-1
          deployment_package: deploy.zip


