name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: idealo-design # Provide only Docker image name, tag will be automatically set to latest
          dockerfile: ./packages/idealo.design/Dockerfile
          
      - name: Temporarily save webpack artifact
        uses: actions/upload-artifact@v2
        with:
          name: webpack-artifact
          path: build
          retention-days: 1
    
    #steps:
    #- uses: actions/checkout@v2
    #- name: Build the Docker image###
      #run: docker build . --file ./packages/idealo.design/Dockerfile --tag lara:$(date +%s
