# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/master' # Running this job only for master branch

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.1.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: my-cool-service # Provide only Docker image name, tag will be automatically set to latest
        dockerfile: Dockerfile_server
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #-
        #name: Set up Docker Buildx
        #uses: docker/setup-buildx-action@v1
      #-
        #name: Build and push
        #id: docker_build
        #uses: docker/build-push-action@v2
        #with:
          #file: ./idealo.design/Dockerfile
          #push: false
          #tags: user/app:latest
      #-
        #name: Image digest
        #run: echo ${{ steps.docker_build.outputs.digest }}
