name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_push_to_registry: #1 
    runs-on: ubuntu-latest #1 
    permissions:
      packages: read
      contents: read
    steps:
      - name: Check out the repo #1
        uses: actions/checkout@v2 #1
      - name: Push to GitHub Packages
        # uses: VaultVulp/gp-docker-action@1.1.8 #1 
        uses: docker/build-push-action@v1
        with: #1 
          image-name: idealodesign #1 
          dockerfile: ./packages/idealo.design/Dockerfile #1
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: docker.pkg.github.com/idealo/nwp/idealo-design2
          tag_with_ref: true
