name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_push_to_registry: #1 
    runs-on: ubuntu-latest #1 
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo #1
        uses: actions/checkout@v2 #1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with: #1 
          dockerfile: ./packages/idealo.design/Dockerfile #1
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
          registry: docker.pkg.github.com
          repository: idealo/nwp/idealo-design
          tag_with_sha: true
          push: true
